# Generated by Django 5.2.8 on 2025-11-22 20:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('usuario', models.CharField(max_length=150, verbose_name='usuario')),
                ('empresa', models.CharField(blank=True, max_length=150, verbose_name='empresa')),
                ('pregunta', models.TextField(verbose_name='pregunta')),
                ('respuesta', models.TextField(blank=True, null=True, verbose_name='respuesta')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='comentario')),
                ('categoria', models.CharField(choices=[('general', 'General'), ('soporte', 'Soporte'), ('facturacion', 'Facturación')], default='general', max_length=50, verbose_name='categoria')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='fecha')),
                ('hora', models.TimeField(default=django.utils.timezone.now, verbose_name='hora')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('respondido', 'Respondido'), ('cerrado', 'Cerrado')], default='abierto', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['-created_at'],
            },
        ),
    ]
