# Generated by Django 5.2.8 on 2025-11-22 20:10

import encuenta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='fecha',
            field=models.DateField(default=encuenta.models.hoy, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='hora',
            field=models.TimeField(default=encuenta.models.ahora, verbose_name='hora'),
        ),
    ]
